spring:
  application:
    name: qa-metrics-portal

  datasource:
    url: ${DATABASE_URL:jdbc:mysql://localhost:3306/qa_metrics_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=America/Bogota&allowPublicKeyRetrieval=true}
    username: ${DATABASE_USER:root}
    password: ${DATABASE_PASS:}
    driver-class-name: ${DATABASE_DRIVER:com.mysql.cj.jdbc.Driver}

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    clean-disabled: false
    clean-on-validation-error: true
    out-of-order: true
    url: ${DATABASE_URL:jdbc:mysql://localhost:3306/qa_metrics_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=America/Bogota&allowPublicKeyRetrieval=true}
    user: ${DATABASE_USER:root}
    password: ${DATABASE_PASS:}

server:
  port: ${PORT:8080}
  servlet:
    context-path: /api/v1

security:
  jwt:
    secret: ${JWT_SECRET:qaMetricsPortalSuperSecretKeyForHMAC256AtLeast256BitsLong2024}
    expiration-ms: ${JWT_EXPIRATION_MS:86400000}  # 24 horas

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method

logging:
  level:
    com.qametrics: DEBUG
    org.springframework.security: INFO
